name: Email Notification

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3

        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}

          subject: Cambios subidos a rama ${{ github.ref_name }}

          body: |
            Se detectaron cambios en la rama:
            ${{ github.ref_name }}

          to: TU_CORREO@gmail.com
          from: GitHub Actions