name: Email Notification

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp+starttls://${{ secrets.EMAIL_USER }}:${{ secrets.EMAIL_PASS }}@smtp.gmail.com:587

          subject: Cambios subidos a rama ${{ github.ref_name }}

          body: |
            Se realizaron cambios en la rama:
            ${{ github.ref_name }}

          to: pablo.portillo.madera@gmail.com
          from: GitHub Actions